quarkus:
  datasource:
    db-kind: mariadb
    username: root
    password: root
    jdbc:
      url: jdbc:mariadb://localhost:3306/todo
    reactive:
      url: vertx-reactive:mysql://localhost:3306/todo
  flyway:
    migrate-at-start: true
  hibernate-orm:
    database:
      generation: drop-and-create

"%dev":
  quarkus:
    flyway:
      repair-at-start: true